# dev profile

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://gos-database:5433/gos
    username: gos
    password: gos

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 4000