# dev profile

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gos
    username: lreas
    password: lreas

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 4000